name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run JSHint
        run: jshint giftlink-backend/**/*.js

      - name: Lint completed
        run: echo "Linting completed successfully"

  client_build:
    name: Build client
    runs-on: ubuntu-latest
    needs: lint_js   # optional: makes build run only after lint passes

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Run build
      run: |
        cd giftlink-frontend
        npm install
        npm run build
        cp -r build ../giftlink-backend/public
        echo "Client-side build successfully"
